// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gf2-demo/internal/logic/demo"
	_ "gf2-demo/internal/logic/middleware"
)
