// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/windvalley/gf2-demo/internal/logic/demo"
	_ "github.com/windvalley/gf2-demo/internal/logic/middleware"
)
