// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sdk

import (
	"fmt"

	"github.com/gogf/gf/contrib/sdk/httpclient/v2"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/text/gstr"
)

type implementer struct {
	config httpclient.Config
}

func New(config httpclient.Config) IClient {
	if !gstr.HasPrefix(config.URL, "http") {
		config.URL = fmt.Sprintf("http://%s", config.URL)
	}
	if config.Logger == nil {
		config.Logger = g.Log()
	}
	return &implementer{
		config: config,
	}
}

